### PR TITLE
Fix the build with volk 3.3

### PR DESCRIPTION
**Pull request by AdrianBunk**
https://buildd.debian.org/status/fetch.php?pkg=satdump&arch=arm64&ver=1.2.2%2Bgb79af48-1%2Bb2&stamp=1771060232&raw=0

```
In file included from /build/reproducible-path/satdump-1.2.2+gb79af48/src-interface/viewer/image_handler.cpp:2:
/usr/include/volk/volk_common.h: In function ‘float volk_cos_poly(float)’:
/build/reproducible-path/satdump-1.2.2+gb79af48/src-interface/../src-core/common/calibration.h:7:12: error: expected unqualified-id before numeric constant
    7 | #define c1 1.1910427e-05
      |            ^~~~~~~~~~~~~
/build/reproducible-path/satdump-1.2.2+gb79af48/src-interface/../src-core/common/calibration.h:8:12: error: expected unqualified-id before numeric constant
    8 | #define c2 1.4387752
      |            ^~~~~~~~~
/usr/include/volk/volk_common.h: In function ‘float volk_arcsin_poly(float)’:
/build/reproducible-path/satdump-1.2.2+gb79af48/src-interface/../src-core/common/calibration.h:7:12: error: expected unqualified-id before numeric constant
    7 | #define c1 1.1910427e-05
      |            ^~~~~~~~~~~~~
/build/reproducible-path/satdump-1.2.2+gb79af48/src-interface/../src-core/common/calibration.h:8:12: error: expected unqualified-id before numeric constant
    8 | #define c2 1.4387752
      |            ^~~~~~~~~
```

the relevant change in volk is https://github.com/gnuradio/volk/commit/5ba6643e4845b56fd26fbf34ff1eeafead312157#diff-92e7a9648c7721918392f95b8c2522e12d51cfc83eb32490e1f1deec71f064e4R235-R236

`c1` and `c2` are too generic identifiers for being used in a define.

### CODE REVIEW

**Comment by Aang23** [comment]
I don't seem to be able to reproduce anymore in the current v2.0.0 (now, master) codebase.

While they are generic, this is also all contained inside a single .cpp file, so it shouldn't normally be a problem.

**Comment by AdrianBunk** [comment]
Yes, it seems this just got fixed by commit 9277d3995daaf09e6560de0d435953377b281544.
